#ifndef EMOJI_H
#define EMOJI_H
#include <Adafruit_SSD1306.h>
#include <string>
#include <vector>



extern std::vector<std::string> emojis;
extern Adafruit_SSD1306 display;

void showEmoji(int index);
void playEmojiBootAnimation();
// Declare each bitmap frame
extern const unsigned char epd_bitmap_00[];
extern const unsigned char epd_bitmap_01[];
extern const unsigned char epd_bitmap_02[];
extern const unsigned char epd_bitmap_03[];
extern const unsigned char epd_bitmap_04[];
extern const unsigned char epd_bitmap_05[];
extern const unsigned char epd_bitmap_06[];
extern const unsigned char epd_bitmap_07[];
extern const unsigned char epd_bitmap_08[];
extern const unsigned char epd_bitmap_09[];
extern const unsigned char epd_bitmap_10[];
extern const unsigned char epd_bitmap_11[];
extern const unsigned char epd_bitmap_12[];
extern const unsigned char epd_bitmap_13[];
extern const unsigned char epd_bitmap_14[];
extern const unsigned char epd_bitmap_15[];
extern const unsigned char epd_bitmap_16[];
extern const unsigned char epd_bitmap_17[];
extern const unsigned char epd_bitmap_18[];
extern const unsigned char epd_bitmap_19[];
extern const unsigned char epd_bitmap_20[];
extern const unsigned char epd_bitmap_21[];
extern const unsigned char epd_bitmap_22[];
extern const unsigned char epd_bitmap_23[];
extern const unsigned char epd_bitmap_24[];
extern const unsigned char epd_bitmap_25[];
extern const unsigned char epd_bitmap_26[];
extern const unsigned char epd_bitmap_27[];
extern const unsigned char epd_bitmap_28[];
extern const unsigned char epd_bitmap_29[];
extern const unsigned char epd_bitmap_30[];
extern const unsigned char epd_bitmap_31[];
extern const unsigned char epd_bitmap_32[];
extern const unsigned char epd_bitmap_33[];
extern const unsigned char epd_bitmap_34[];
extern const unsigned char epd_bitmap_35[];
extern const unsigned char epd_bitmap_36[];
extern const unsigned char epd_bitmap_37[];
extern const unsigned char epd_bitmap_38[];
extern const unsigned char epd_bitmap_39[];
extern const unsigned char epd_bitmap_40[];
extern const unsigned char epd_bitmap_41[];
extern const unsigned char epd_bitmap_42[];
extern const unsigned char epd_bitmap_43[];
extern const unsigned char epd_bitmap_44[];
extern const unsigned char epd_bitmap_45[];
extern const unsigned char epd_bitmap_46[];
extern const unsigned char epd_bitmap_47[];
extern const unsigned char epd_bitmap_48[];
extern const unsigned char epd_bitmap_49[];
extern const unsigned char epd_bitmap_50[];
extern const unsigned char epd_bitmap_51[];
extern const unsigned char epd_bitmap_52[];
extern const unsigned char epd_bitmap_53[];
extern const unsigned char epd_bitmap_54[];
extern const unsigned char epd_bitmap_55[];
extern const unsigned char epd_bitmap_56[];
extern const unsigned char epd_bitmap_57[];
extern const unsigned char epd_bitmap_58[];
extern const unsigned char epd_bitmap_59[];
extern const unsigned char epd_bitmap_60[];

extern const unsigned char epd_bitmap01_00[];
extern const unsigned char epd_bitmap01_01[];
extern const unsigned char epd_bitmap01_02[];   
extern const unsigned char epd_bitmap01_03[];
extern const unsigned char epd_bitmap01_04[];
extern const unsigned char epd_bitmap01_05[];
extern const unsigned char epd_bitmap01_06[];
extern const unsigned char epd_bitmap01_07[];
extern const unsigned char epd_bitmap01_08[];
extern const unsigned char epd_bitmap01_09[];
extern const unsigned char epd_bitmap01_10[];
extern const unsigned char epd_bitmap01_11[];
extern const unsigned char epd_bitmap01_12[];
extern const unsigned char epd_bitmap01_13[];
extern const unsigned char epd_bitmap01_14[];
extern const unsigned char epd_bitmap01_15[];
extern const unsigned char epd_bitmap01_16[];
extern const unsigned char epd_bitmap01_17[];
extern const unsigned char epd_bitmap01_18[];
extern const unsigned char epd_bitmap01_19[];
extern const unsigned char epd_bitmap01_20[];
extern const unsigned char epd_bitmap01_21[];
extern const unsigned char epd_bitmap01_22[];
extern const unsigned char epd_bitmap01_23[];
extern const unsigned char epd_bitmap01_24[];
extern const unsigned char epd_bitmap01_25[];
extern const unsigned char epd_bitmap01_26[];
extern const unsigned char epd_bitmap01_27[];
extern const unsigned char epd_bitmap01_28[];
extern const unsigned char epd_bitmap01_29[];
extern const unsigned char epd_bitmap01_30[];
extern const unsigned char epd_bitmap01_31[];
extern const unsigned char epd_bitmap01_32[];
extern const unsigned char epd_bitmap01_33[];
extern const unsigned char epd_bitmap01_34[];
extern const unsigned char epd_bitmap01_35[];
extern const unsigned char epd_bitmap01_36[];
extern const unsigned char epd_bitmap01_37[];
extern const unsigned char epd_bitmap01_38[];
extern const unsigned char epd_bitmap01_39[];
extern const unsigned char epd_bitmap01_40[];
extern const unsigned char epd_bitmap01_41[];
extern const unsigned char epd_bitmap01_42[];
extern const unsigned char epd_bitmap01_43[];
extern const unsigned char epd_bitmap01_44[];
extern const unsigned char epd_bitmap01_45[];
extern const unsigned char epd_bitmap01_46[];
extern const unsigned char epd_bitmap01_47[];
extern const unsigned char epd_bitmap01_48[];
extern const unsigned char epd_bitmap01_49[];
extern const unsigned char epd_bitmap01_50[];
extern const unsigned char epd_bitmap01_51[];
extern const unsigned char epd_bitmap01_52[];
extern const unsigned char epd_bitmap01_53[];
extern const unsigned char epd_bitmap01_54[];
extern const unsigned char epd_bitmap01_55[];
extern const unsigned char epd_bitmap01_56[];
extern const unsigned char epd_bitmap01_57[];
extern const unsigned char epd_bitmap01_58[];
extern const unsigned char epd_bitmap01_59[];
extern const unsigned char epd_bitmap01_60[];
extern const unsigned char epd_bitmap01_61[];
extern const unsigned char epd_bitmap01_62[];
extern const unsigned char epd_bitmap01_63[];
extern const unsigned char epd_bitmap01_64[];
extern const unsigned char epd_bitmap01_65[];
extern const unsigned char epd_bitmap01_66[];
extern const unsigned char epd_bitmap01_67[];
extern const unsigned char epd_bitmap01_68[];
extern const unsigned char epd_bitmap01_69[];
extern const unsigned char epd_bitmap01_70[];
extern const unsigned char epd_bitmap01_71[];
extern const unsigned char epd_bitmap01_72[];
extern const unsigned char epd_bitmap01_73[];
extern const unsigned char epd_bitmap01_74[];
extern const unsigned char epd_bitmap01_75[];
extern const unsigned char epd_bitmap01_76[];
extern const unsigned char epd_bitmap01_77[];
extern const unsigned char epd_bitmap01_78[];
extern const unsigned char epd_bitmap01_79[];
extern const unsigned char epd_bitmap01_80[];
extern const unsigned char epd_bitmap01_81[];
extern const unsigned char epd_bitmap01_82[];
extern const unsigned char epd_bitmap01_83[];
extern const unsigned char epd_bitmap01_84[];
extern const unsigned char epd_bitmap01_85[];
extern const unsigned char epd_bitmap01_86[];
extern const unsigned char epd_bitmap01_87[];
extern const unsigned char epd_bitmap01_88[];
extern const unsigned char epd_bitmap01_89[];
extern const unsigned char epd_bitmap01_90[];

extern const unsigned char epd_bitmap02_00[];
extern const unsigned char epd_bitmap02_01[];
extern const unsigned char epd_bitmap02_02[];
extern const unsigned char epd_bitmap02_03[];
extern const unsigned char epd_bitmap02_04[];
extern const unsigned char epd_bitmap02_05[];
extern const unsigned char epd_bitmap02_06[];
extern const unsigned char epd_bitmap02_07[];
extern const unsigned char epd_bitmap02_08[];
extern const unsigned char epd_bitmap02_09[];
extern const unsigned char epd_bitmap02_10[];
extern const unsigned char epd_bitmap02_11[];
extern const unsigned char epd_bitmap02_12[];
extern const unsigned char epd_bitmap02_13[];
extern const unsigned char epd_bitmap02_14[];
extern const unsigned char epd_bitmap02_15[];
extern const unsigned char epd_bitmap02_16[];
extern const unsigned char epd_bitmap02_17[];
extern const unsigned char epd_bitmap02_18[];
extern const unsigned char epd_bitmap02_19[];
extern const unsigned char epd_bitmap02_20[];
extern const unsigned char epd_bitmap02_21[];
extern const unsigned char epd_bitmap02_22[];
extern const unsigned char epd_bitmap02_23[];
extern const unsigned char epd_bitmap02_24[];
extern const unsigned char epd_bitmap02_25[];
extern const unsigned char epd_bitmap02_26[];
extern const unsigned char epd_bitmap02_27[];
extern const unsigned char epd_bitmap02_28[];
extern const unsigned char epd_bitmap02_29[];
extern const unsigned char epd_bitmap02_30[];
extern const unsigned char epd_bitmap02_31[];
extern const unsigned char epd_bitmap02_32[];
extern const unsigned char epd_bitmap02_33[];
extern const unsigned char epd_bitmap02_34[];
extern const unsigned char epd_bitmap02_35[];
extern const unsigned char epd_bitmap02_36[];
extern const unsigned char epd_bitmap02_37[];
extern const unsigned char epd_bitmap02_38[];
extern const unsigned char epd_bitmap02_39[];
extern const unsigned char epd_bitmap02_40[];
extern const unsigned char epd_bitmap02_41[];
extern const unsigned char epd_bitmap02_42[];
extern const unsigned char epd_bitmap02_43[];
extern const unsigned char epd_bitmap02_44[];
extern const unsigned char epd_bitmap02_45[];
extern const unsigned char epd_bitmap02_46[];
extern const unsigned char epd_bitmap02_47[];
extern const unsigned char epd_bitmap02_48[];
extern const unsigned char epd_bitmap02_49[];
extern const unsigned char epd_bitmap02_50[];
extern const unsigned char epd_bitmap02_51[];
extern const unsigned char epd_bitmap02_52[];
extern const unsigned char epd_bitmap02_53[];
extern const unsigned char epd_bitmap02_54[];
extern const unsigned char epd_bitmap02_55[];
extern const unsigned char epd_bitmap02_56[];
extern const unsigned char epd_bitmap02_57[];
extern const unsigned char epd_bitmap02_58[];
extern const unsigned char epd_bitmap02_59[];
extern const unsigned char epd_bitmap02_60[];
extern const unsigned char epd_bitmap02_61[];
extern const unsigned char epd_bitmap02_62[];
extern const unsigned char epd_bitmap02_63[];
extern const unsigned char epd_bitmap02_64[];
extern const unsigned char epd_bitmap02_65[];
extern const unsigned char epd_bitmap02_66[];
extern const unsigned char epd_bitmap02_67[];
extern const unsigned char epd_bitmap02_68[];
extern const unsigned char epd_bitmap02_69[];
extern const unsigned char epd_bitmap02_70[];

// // Array of all bitmaps
// extern const unsigned char* epd_bitmap_allArray[61];
// extern const int epd_bitmap_allArray_LEN;
// // Array of idle screen bitmaps
// extern const unsigned char* epd_bitmap01_allArray[91];
// extern const int epd_bitmap01_allArray_LEN;
// //Array of gyro response bitmaps
// extern const unsigned char* epd_bitmap02_allArray[70];
// extern const int epd_bitmap02_allArray_LEN;

extern const int epd_bootanimation_allArray_LEN;
extern const unsigned char* epd_bootanimation_allArray[541];
#endif // EMOJI_H
