#ifndef EMOJI_H
#define EMOJI_H
#include "interface.h"

struct Animation {
  const unsigned char** frames;
  int frameCount;
};
extern Animation allAnimations[];
extern const int totalAnimations;

// Declare each individual frame used in the sleeping animation
extern const unsigned char sleeping_00[];
extern const unsigned char sleeping_01[];
extern const unsigned char sleeping_02[];
extern const unsigned char sleeping_03[];
extern const unsigned char sleeping_04[];
extern const unsigned char sleeping_05[];
extern const unsigned char sleeping_06[];
extern const unsigned char sleeping_07[];
extern const unsigned char sleeping_08[];
extern const unsigned char sleeping_09[];
extern const unsigned char sleeping_10[];
extern const unsigned char sleeping_11[];
extern const unsigned char sleeping_12[];
extern const unsigned char sleeping_13[];
extern const unsigned char sleeping_14[];
extern const unsigned char sleeping_15[];
extern const unsigned char sleeping_16[];
extern const unsigned char sleeping_17[];
extern const unsigned char sleeping_18[];
extern const unsigned char sleeping_19[];
extern const unsigned char sleeping_20[];
extern const unsigned char sleeping_21[];
extern const unsigned char sleeping_22[];
extern const unsigned char sleeping_23[];
extern const unsigned char sleeping_24[];
extern const unsigned char sleeping_25[];
extern const unsigned char sleeping_26[];
extern const unsigned char sleeping_27[];
extern const unsigned char sleeping_28[];
extern const unsigned char sleeping_29[];
extern const unsigned char sleeping_30[];
extern const unsigned char sleeping_31[];
extern const unsigned char sleeping_32[];
extern const unsigned char sleeping_33[];
extern const unsigned char sleeping_34[];
extern const unsigned char sleeping_35[];
extern const unsigned char sleeping_36[];
extern const unsigned char sleeping_37[];
extern const unsigned char sleeping_38[];
extern const unsigned char sleeping_39[];
extern const unsigned char sleeping_40[];
extern const unsigned char sleeping_41[];
extern const unsigned char sleeping_42[];
extern const unsigned char sleeping_43[];
extern const unsigned char sleeping_44[];
extern const unsigned char sleeping_45[];
extern const unsigned char sleeping_46[];
extern const unsigned char sleeping_47[];
extern const unsigned char sleeping_48[];
extern const unsigned char sleeping_49[];
extern const unsigned char sleeping_50[];

extern const int sleeping_allArray_LEN;
extern const unsigned char* sleeping_allArray[51];

extern const unsigned char hearteyes_00[];
extern const unsigned char hearteyes_01[];
extern const unsigned char hearteyes_02[];
extern const unsigned char hearteyes_03[];
extern const unsigned char hearteyes_04[];
extern const unsigned char hearteyes_05[];
extern const unsigned char hearteyes_06[];
extern const unsigned char hearteyes_07[];
extern const unsigned char hearteyes_08[];
extern const unsigned char hearteyes_09[];
extern const unsigned char hearteyes_10[];
extern const unsigned char hearteyes_11[];
extern const unsigned char hearteyes_12[];
extern const unsigned char hearteyes_13[];
extern const unsigned char hearteyes_14[];
extern const unsigned char hearteyes_15[];
extern const unsigned char hearteyes_16[];
extern const unsigned char hearteyes_17[];
extern const unsigned char hearteyes_18[];
extern const unsigned char hearteyes_19[];
extern const unsigned char hearteyes_20[];
extern const unsigned char hearteyes_21[];
extern const unsigned char hearteyes_22[];
extern const unsigned char hearteyes_23[];
extern const unsigned char hearteyes_24[];
extern const unsigned char hearteyes_25[];
extern const unsigned char hearteyes_26[];
extern const unsigned char hearteyes_27[];
extern const unsigned char hearteyes_28[];
extern const unsigned char hearteyes_29[];
extern const unsigned char hearteyes_30[];
extern const unsigned char hearteyes_31[];
extern const unsigned char hearteyes_32[];
extern const unsigned char hearteyes_33[];
extern const unsigned char hearteyes_34[];
extern const unsigned char hearteyes_35[];
extern const unsigned char hearteyes_36[];
extern const unsigned char hearteyes_37[];
extern const unsigned char hearteyes_38[];
extern const unsigned char hearteyes_39[];
extern const unsigned char hearteyes_40[];
extern const unsigned char hearteyes_41[];
extern const unsigned char hearteyes_42[];
extern const unsigned char hearteyes_43[];
extern const unsigned char hearteyes_44[];
extern const unsigned char hearteyes_45[];
extern const unsigned char hearteyes_46[];
extern const unsigned char hearteyes_47[];
extern const unsigned char hearteyes_48[];
extern const unsigned char hearteyes_49[];
extern const unsigned char hearteyes_50[];
extern const unsigned char hearteyes_51[];
extern const unsigned char hearteyes_52[];
extern const unsigned char hearteyes_53[];
extern const unsigned char hearteyes_54[];
extern const unsigned char hearteyes_55[];
extern const unsigned char hearteyes_56[];
extern const unsigned char hearteyes_57[];
extern const unsigned char hearteyes_58[];
extern const unsigned char hearteyes_59[];
extern const unsigned char hearteyes_60[];

extern const int hearteyes_allArray_LEN;
extern const unsigned char* hearteyes_allArray[61];

extern const unsigned char leftside_00[];
extern const unsigned char leftside_01[];
extern const unsigned char leftside_02[];
extern const unsigned char leftside_03[];
extern const unsigned char leftside_04[];
extern const unsigned char leftside_05[];
extern const unsigned char leftside_06[];
extern const unsigned char leftside_07[];
extern const unsigned char leftside_08[];
extern const unsigned char leftside_09[];
extern const unsigned char leftside_10[];
extern const unsigned char leftside_11[];
extern const unsigned char leftside_12[];
extern const unsigned char leftside_13[];
extern const unsigned char leftside_14[];
extern const unsigned char leftside_15[];
extern const unsigned char leftside_16[];
extern const unsigned char leftside_17[];
extern const unsigned char leftside_18[];
extern const unsigned char leftside_19[];
extern const unsigned char leftside_20[];
extern const unsigned char leftside_21[];
extern const unsigned char leftside_22[];
extern const unsigned char leftside_23[];
extern const unsigned char leftside_24[];
extern const unsigned char leftside_25[];
extern const unsigned char leftside_26[];
extern const unsigned char leftside_27[];
extern const unsigned char leftside_28[];
extern const unsigned char leftside_29[];
extern const unsigned char leftside_30[];
extern const unsigned char leftside_31[];
extern const unsigned char leftside_32[];
extern const unsigned char leftside_33[];
extern const unsigned char leftside_34[];
extern const unsigned char leftside_35[];
extern const unsigned char leftside_36[];
extern const unsigned char leftside_37[];
extern const unsigned char leftside_38[];
extern const unsigned char leftside_39[];
extern const unsigned char leftside_40[];
extern const unsigned char leftside_41[];
extern const unsigned char leftside_42[];
extern const unsigned char leftside_43[];
extern const unsigned char leftside_44[];
extern const unsigned char leftside_45[];
extern const unsigned char leftside_46[];
extern const unsigned char leftside_47[];
extern const unsigned char leftside_48[];
extern const unsigned char leftside_49[];
extern const unsigned char leftside_50[];
extern const unsigned char leftside_51[];
extern const unsigned char leftside_52[];
extern const unsigned char leftside_53[];
extern const unsigned char leftside_54[];
extern const unsigned char leftside_55[];
extern const unsigned char leftside_56[];
extern const unsigned char leftside_57[];
extern const unsigned char leftside_58[];
extern const unsigned char leftside_59[];
extern const unsigned char leftside_60[];

extern const int leftside_allArray_LEN;
extern const unsigned char* leftside_allArray[61];

extern const unsigned char rightside_00[];
extern const unsigned char rightside_01[];
extern const unsigned char rightside_02[];
extern const unsigned char rightside_03[];
extern const unsigned char rightside_04[];
extern const unsigned char rightside_05[];
extern const unsigned char rightside_06[];
extern const unsigned char rightside_07[];
extern const unsigned char rightside_08[];
extern const unsigned char rightside_09[];
extern const unsigned char rightside_10[];
extern const unsigned char rightside_11[];
extern const unsigned char rightside_12[];
extern const unsigned char rightside_13[];
extern const unsigned char rightside_14[];
extern const unsigned char rightside_15[];
extern const unsigned char rightside_16[];
extern const unsigned char rightside_17[];
extern const unsigned char rightside_18[];
extern const unsigned char rightside_19[];
extern const unsigned char rightside_20[];
extern const unsigned char rightside_21[];
extern const unsigned char rightside_22[];
extern const unsigned char rightside_23[];
extern const unsigned char rightside_24[];
extern const unsigned char rightside_25[];
extern const unsigned char rightside_26[];
extern const unsigned char rightside_27[];
extern const unsigned char rightside_28[];
extern const unsigned char rightside_29[];
extern const unsigned char rightside_30[];
extern const unsigned char rightside_31[];
extern const unsigned char rightside_32[];
extern const unsigned char rightside_33[];
extern const unsigned char rightside_34[];
extern const unsigned char rightside_35[];
extern const unsigned char rightside_36[];
extern const unsigned char rightside_37[];
extern const unsigned char rightside_38[];
extern const unsigned char rightside_39[];
extern const unsigned char rightside_40[];
extern const unsigned char rightside_41[];
extern const unsigned char rightside_42[];
extern const unsigned char rightside_43[];
extern const unsigned char rightside_44[];
extern const unsigned char rightside_45[];
extern const unsigned char rightside_46[];
extern const unsigned char rightside_47[];
extern const unsigned char rightside_48[];
extern const unsigned char rightside_49[];
extern const unsigned char rightside_50[];
extern const unsigned char rightside_51[];
extern const unsigned char rightside_52[];
extern const unsigned char rightside_53[];
extern const unsigned char rightside_54[];
extern const unsigned char rightside_55[];
extern const unsigned char rightside_56[];
extern const unsigned char rightside_57[];
extern const unsigned char rightside_58[];
extern const unsigned char rightside_59[];
extern const unsigned char rightside_60[];

extern const int rightside_allArray_LEN;
extern const unsigned char* rightside_allArray[61];

extern const unsigned char flashyeyes_000[];
extern const unsigned char flashyeyes_001[];
extern const unsigned char flashyeyes_002[];
extern const unsigned char flashyeyes_003[];
extern const unsigned char flashyeyes_004[];
extern const unsigned char flashyeyes_005[];
extern const unsigned char flashyeyes_006[];
extern const unsigned char flashyeyes_007[];
extern const unsigned char flashyeyes_008[];
extern const unsigned char flashyeyes_009[];

extern const unsigned char flashyeyes_010[];
extern const unsigned char flashyeyes_011[];
extern const unsigned char flashyeyes_012[];
extern const unsigned char flashyeyes_013[];
extern const unsigned char flashyeyes_014[];
extern const unsigned char flashyeyes_015[];
extern const unsigned char flashyeyes_016[];
extern const unsigned char flashyeyes_017[];
extern const unsigned char flashyeyes_018[];
extern const unsigned char flashyeyes_019[];

extern const unsigned char flashyeyes_020[];
extern const unsigned char flashyeyes_021[];
extern const unsigned char flashyeyes_022[];
extern const unsigned char flashyeyes_023[];
extern const unsigned char flashyeyes_024[];
extern const unsigned char flashyeyes_025[];
extern const unsigned char flashyeyes_026[];
extern const unsigned char flashyeyes_027[];
extern const unsigned char flashyeyes_028[];
extern const unsigned char flashyeyes_029[];

extern const unsigned char flashyeyes_030[];
extern const unsigned char flashyeyes_031[];
extern const unsigned char flashyeyes_032[];
extern const unsigned char flashyeyes_033[];
extern const unsigned char flashyeyes_034[];
extern const unsigned char flashyeyes_035[];
extern const unsigned char flashyeyes_036[];
extern const unsigned char flashyeyes_037[];
extern const unsigned char flashyeyes_038[];
extern const unsigned char flashyeyes_039[];

extern const unsigned char flashyeyes_040[];
extern const unsigned char flashyeyes_041[];
extern const unsigned char flashyeyes_042[];
extern const unsigned char flashyeyes_043[];
extern const unsigned char flashyeyes_044[];
extern const unsigned char flashyeyes_045[];
extern const unsigned char flashyeyes_046[];
extern const unsigned char flashyeyes_047[];
extern const unsigned char flashyeyes_048[];
extern const unsigned char flashyeyes_049[];

extern const unsigned char flashyeyes_050[];
extern const unsigned char flashyeyes_051[];
extern const unsigned char flashyeyes_052[];
extern const unsigned char flashyeyes_053[];
extern const unsigned char flashyeyes_054[];
extern const unsigned char flashyeyes_055[];
extern const unsigned char flashyeyes_056[];
extern const unsigned char flashyeyes_057[];
extern const unsigned char flashyeyes_058[];
extern const unsigned char flashyeyes_059[];

extern const unsigned char flashyeyes_060[];
extern const unsigned char flashyeyes_061[];
extern const unsigned char flashyeyes_062[];
extern const unsigned char flashyeyes_063[];
extern const unsigned char flashyeyes_064[];
extern const unsigned char flashyeyes_065[];
extern const unsigned char flashyeyes_066[];
extern const unsigned char flashyeyes_067[];
extern const unsigned char flashyeyes_068[];
extern const unsigned char flashyeyes_069[];

extern const unsigned char flashyeyes_070[];
extern const unsigned char flashyeyes_071[];
extern const unsigned char flashyeyes_072[];
extern const unsigned char flashyeyes_073[];
extern const unsigned char flashyeyes_074[];
extern const unsigned char flashyeyes_075[];
extern const unsigned char flashyeyes_076[];
extern const unsigned char flashyeyes_077[];
extern const unsigned char flashyeyes_078[];
extern const unsigned char flashyeyes_079[];

extern const unsigned char flashyeyes_080[];
extern const unsigned char flashyeyes_081[];
extern const unsigned char flashyeyes_082[];
extern const unsigned char flashyeyes_083[];
extern const unsigned char flashyeyes_084[];
extern const unsigned char flashyeyes_085[];
extern const unsigned char flashyeyes_086[];
extern const unsigned char flashyeyes_087[];
extern const unsigned char flashyeyes_088[];
extern const unsigned char flashyeyes_089[];

extern const unsigned char flashyeyes_090[];
extern const unsigned char flashyeyes_091[];
extern const unsigned char flashyeyes_092[];
extern const unsigned char flashyeyes_093[];
extern const unsigned char flashyeyes_094[];
extern const unsigned char flashyeyes_095[];
extern const unsigned char flashyeyes_096[];
extern const unsigned char flashyeyes_097[];
extern const unsigned char flashyeyes_098[];
extern const unsigned char flashyeyes_099[];

extern const unsigned char flashyeyes_100[];
extern const unsigned char flashyeyes_101[];
extern const unsigned char flashyeyes_102[];
extern const unsigned char flashyeyes_103[];
extern const unsigned char flashyeyes_104[];
extern const unsigned char flashyeyes_105[];
extern const unsigned char flashyeyes_106[];
extern const unsigned char flashyeyes_107[];
extern const unsigned char flashyeyes_108[];
extern const unsigned char flashyeyes_109[];

extern const unsigned char flashyeyes_110[];
extern const unsigned char flashyeyes_111[];
extern const unsigned char flashyeyes_112[];
extern const unsigned char flashyeyes_113[];
extern const unsigned char flashyeyes_114[];
extern const unsigned char flashyeyes_115[];
extern const unsigned char flashyeyes_116[];
extern const unsigned char flashyeyes_117[];
extern const unsigned char flashyeyes_118[];
extern const unsigned char flashyeyes_119[];

extern const unsigned char flashyeyes_120[];
extern const unsigned char flashyeyes_121[];
extern const unsigned char flashyeyes_122[];
extern const unsigned char flashyeyes_123[];
extern const unsigned char flashyeyes_124[];
extern const unsigned char flashyeyes_125[];
extern const unsigned char flashyeyes_126[];
extern const unsigned char flashyeyes_127[];
extern const unsigned char flashyeyes_128[];
extern const unsigned char flashyeyes_129[];

extern const unsigned char flashyeyes_130[];
extern const unsigned char flashyeyes_131[];
extern const unsigned char flashyeyes_132[];
extern const unsigned char flashyeyes_133[];
extern const unsigned char flashyeyes_134[];
extern const unsigned char flashyeyes_135[];
extern const unsigned char flashyeyes_136[];
extern const unsigned char flashyeyes_137[];
extern const unsigned char flashyeyes_138[];
extern const unsigned char flashyeyes_139[];

extern const unsigned char flashyeyes_140[];
extern const unsigned char flashyeyes_141[];
extern const unsigned char flashyeyes_142[];
extern const unsigned char flashyeyes_143[];
extern const unsigned char flashyeyes_144[];
extern const unsigned char flashyeyes_145[];
extern const unsigned char flashyeyes_146[];
extern const unsigned char flashyeyes_147[];
extern const unsigned char flashyeyes_148[];
extern const unsigned char flashyeyes_149[];
extern const unsigned char flashyeyes_150[];

extern const int flashyeyes_allArray_LEN;
extern const unsigned char* flashyeyes_allArray[151];

extern const unsigned char dizzy_00[];
extern const unsigned char dizzy_01[];
extern const unsigned char dizzy_02[];
extern const unsigned char dizzy_03[];
extern const unsigned char dizzy_04[];
extern const unsigned char dizzy_05[];
extern const unsigned char dizzy_06[];
extern const unsigned char dizzy_07[];
extern const unsigned char dizzy_08[];
extern const unsigned char dizzy_09[];

extern const unsigned char dizzy_10[];
extern const unsigned char dizzy_11[];
extern const unsigned char dizzy_12[];
extern const unsigned char dizzy_13[];
extern const unsigned char dizzy_14[];
extern const unsigned char dizzy_15[];
extern const unsigned char dizzy_16[];
extern const unsigned char dizzy_17[];
extern const unsigned char dizzy_18[];
extern const unsigned char dizzy_19[];

extern const unsigned char dizzy_20[];
extern const unsigned char dizzy_21[];
extern const unsigned char dizzy_22[];
extern const unsigned char dizzy_23[];
extern const unsigned char dizzy_24[];
extern const unsigned char dizzy_25[];
extern const unsigned char dizzy_26[];
extern const unsigned char dizzy_27[];
extern const unsigned char dizzy_28[];
extern const unsigned char dizzy_29[];

extern const unsigned char dizzy_30[];
extern const unsigned char dizzy_31[];
extern const unsigned char dizzy_32[];
extern const unsigned char dizzy_33[];
extern const unsigned char dizzy_34[];
extern const unsigned char dizzy_35[];
extern const unsigned char dizzy_36[];
extern const unsigned char dizzy_37[];
extern const unsigned char dizzy_38[];
extern const unsigned char dizzy_39[];

extern const unsigned char dizzy_40[];
extern const unsigned char dizzy_41[];
extern const unsigned char dizzy_42[];
extern const unsigned char dizzy_43[];
extern const unsigned char dizzy_44[];
extern const unsigned char dizzy_45[];
extern const unsigned char dizzy_46[];
extern const unsigned char dizzy_47[];
extern const unsigned char dizzy_48[];
extern const unsigned char dizzy_49[];
extern const unsigned char dizzy_50[];

extern const int dizzy_allArray_LEN;
extern const unsigned char* dizzy_allArray[51];

extern const unsigned char boot_00[];
extern const unsigned char boot_01[];
extern const unsigned char boot_02[];
extern const unsigned char boot_03[];
extern const unsigned char boot_04[];
extern const unsigned char boot_05[];
extern const unsigned char boot_06[];
extern const unsigned char boot_07[];
extern const unsigned char boot_08[];
extern const unsigned char boot_09[];

extern const unsigned char boot_10[];
extern const unsigned char boot_11[];
extern const unsigned char boot_12[];
extern const unsigned char boot_13[];
extern const unsigned char boot_14[];
extern const unsigned char boot_15[];
extern const unsigned char boot_16[];
extern const unsigned char boot_17[];
extern const unsigned char boot_18[];
extern const unsigned char boot_19[];

extern const unsigned char boot_20[];
extern const unsigned char boot_21[];
extern const unsigned char boot_22[];
extern const unsigned char boot_23[];
extern const unsigned char boot_24[];
extern const unsigned char boot_25[];
extern const unsigned char boot_26[];
extern const unsigned char boot_27[];
extern const unsigned char boot_28[];
extern const unsigned char boot_29[];

extern const unsigned char boot_30[];
extern const unsigned char boot_31[];
extern const unsigned char boot_32[];
extern const unsigned char boot_33[];
extern const unsigned char boot_34[];
extern const unsigned char boot_35[];
extern const unsigned char boot_36[];
extern const unsigned char boot_37[];
extern const unsigned char boot_38[];
extern const unsigned char boot_39[];

extern const unsigned char boot_40[];
extern const unsigned char boot_41[];
extern const unsigned char boot_42[];
extern const unsigned char boot_43[];
extern const unsigned char boot_44[];
extern const unsigned char boot_45[];
extern const unsigned char boot_46[];
extern const unsigned char boot_47[];
extern const unsigned char boot_48[];
extern const unsigned char boot_49[];

extern const unsigned char boot_50[];
extern const unsigned char boot_51[];
extern const unsigned char boot_52[];
extern const unsigned char boot_53[];
extern const unsigned char boot_54[];
extern const unsigned char boot_55[];
extern const unsigned char boot_56[];
extern const unsigned char boot_57[];
extern const unsigned char boot_58[];
extern const unsigned char boot_59[];
extern const unsigned char boot_60[];

extern const int boot_allArray_LEN;
extern const unsigned char* boot_allArray[61];

#endif // EMOJI_H